// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBem9cJCEWRniPhoBPnMKoK0yYOTl2f8Bg',
    appId: '1:962906869863:web:881850503009d9ba9884c2',
    messagingSenderId: '962906869863',
    projectId: 'spairo-d2511',
    authDomain: 'spairo-d2511.firebaseapp.com',
    storageBucket: 'spairo-d2511.firebasestorage.app',
    measurementId: 'G-LSGV2H311C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmxkAaxTV0C_UWGNW-30Y4tSwvoqcua-k',
    appId: '1:962906869863:android:501338efb4cfe67c9884c2',
    messagingSenderId: '962906869863',
    projectId: 'spairo-d2511',
    storageBucket: 'spairo-d2511.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWgIy5FRVrjyjy7XYMLbkK3IQREK8RUE',
    appId: '1:962906869863:ios:63f9a3299d82f82d9884c2',
    messagingSenderId: '962906869863',
    projectId: 'spairo-d2511',
    storageBucket: 'spairo-d2511.firebasestorage.app',
    iosBundleId: 'com.example.sparioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWgIy5FRVrjyjy7XYMLbkK3IQREK8RUE',
    appId: '1:962906869863:ios:63f9a3299d82f82d9884c2',
    messagingSenderId: '962906869863',
    projectId: 'spairo-d2511',
    storageBucket: 'spairo-d2511.firebasestorage.app',
    iosBundleId: 'com.example.sparioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBem9cJCEWRniPhoBPnMKoK0yYOTl2f8Bg',
    appId: '1:962906869863:web:ca5dfdab4d541f369884c2',
    messagingSenderId: '962906869863',
    projectId: 'spairo-d2511',
    authDomain: 'spairo-d2511.firebaseapp.com',
    storageBucket: 'spairo-d2511.firebasestorage.app',
    measurementId: 'G-5NV3FPB9PD',
  );
}
